apiVersion: ENC[AES256_GCM,data:9Z0=,iv:oKhJh0EmDSpeTcQhT2hPdmA0DYuzXI0xiG20j9T2HOE=,tag:gpwgZWLhHN3v51OaGr1dkQ==,type:str]
kind: ENC[AES256_GCM,data:zfGxu11w,iv:WvWMsiBCnCymXWgq67Pa1Ba1saXS2NQej9ZpWwkZibY=,tag:p25+ntPknItrgORHIcJ7PA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oo1XktXUdO2E41YNCTOGv3TxImLNyssKcboheO3G,iv:HGt014HV70SI0zAvkMEkMcWOUynKDr7IyK5SW3/LwlQ=,tag:t2Zxlbtxo8iScgX+CwIadQ==,type:str]
    namespace: ENC[AES256_GCM,data:oxMQ7iWjIU6VHc7HSoEo,iv:LrGzDQGIJ1G1Sl9ONbk6yJFmJTfAMjvDEfweh2QefBM=,tag:W9cM89HjL+qXLqMQdnaWhQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:+14uNe+hYPFFDIiZAJr5D5AZxBukm+yAdGghRj8B2bI2nzDM7eLBJnWkuQZv5Jx9HYc80YbGHyMprGQzkyxJ857AGChE8VFcabDm7R4+QxQtE3Erz3D5qsAAPYAkfA6NysrWLFpfdVKYuKaMT+EmYB44v+aaByizjM+GSrUSoELFa/jtg5m5VuFvdZxm08/aOU6gIxo54j0rAYpB38H0dYZlD8heRYugyTrJ0kdW/KwWoN0tAFkEaGU8ASNgGNL5jvON/TW0g/bOA01aew27qHZfv//xDhNo9qJSkP70z4QEpVeP+YHP9SyvWhtST8m7ew7li8iAbEZ+Mvj5MTypD9lD/CvsvR/VEKF8Ae8JDp9KvhM/EF3SxMoRtQX0shJ8wo9CIlpSjhCLHmEGwbtDY061xhBjGmn8sqXuHMrcSZYOq37M9u0BzZNo67HD5FzVybJfkZjPR3rWerJBvCslGok1bBAaVIGqSMoP7rJUrYMbPTesli7wxcvPAz/DHlpYWdHqOCA84rkft5dxIx/HhmQkYLLfX05WrTcmIphRx7QL9c/OTNswn/q8i5GiSEW4Qxchgj0mFwH5U7OddvM6A8bykDrB3ZEMS4/UAiN3vJ8gXNCgFsgZkym+hzlinD/7NiXv7uO+h1Ng6A0I2Nv4CFVhlm3eWlv9jz9InHmpxEB8cKVRBHMqmcNwiyNkNRAU65CsP/mRdLXH7Oe5amyGo0gULnjs+sA0U6o=,iv:fqEgpO5zPckmabMdb9j4ZEliXYSnheW1ISnbSXsFSfc=,tag:BqFLbTii78vJZgpAsJnTMg==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMDFiMnVYTUloSDI0RUJG
            MGFXdGJQUWJCdUxVVFdRZ2s0RzJTTEtaNW40CjBTZFRYcW1wa2t4bVJxTUZTNHFK
            MXpzRDVmRjdGV0FHTEcvcFBtRFpHbjQKLS0tIC94QlZWNytFOERmcXFOd3d1cGIw
            d3hETVFKM3YzTDhFUEpNMjBIMENoYmsKkth71Xy03k5cGJPLYD6VYIusF5DZaO7b
            Bpv7nU2pMOfvWM2aYR6rvlMeZwIwT/s3i8AUwEQk5+t38leJIoH9Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOXRMeUZieHpuRlZZNm5Z
            UkNlNFE4UkpieGFxYU1QeTdqMzYweUU1WVRJCjFyZjZqbmNIVUVCN3dhaVdYUnFP
            QXZRZnc1TmZkcWo3eTJBdWs4aEZpc0EKLS0tIGpDZWwrV043K3U2L05OeERwL1ZY
            ZC95K291TDdBdmVPaHVIU0QzQ0c5RFUKirhH4n5Cy+zyYFH1VwfuUGRuuoqWL+1c
            nOF6ipJ3T58lKlAb+rExRxoyss0IzxqpJ3B6i7DBYoYqM/4nXm3AlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T00:27:11Z"
    mac: ENC[AES256_GCM,data:2nmJVh+O/0WBJHVdAHR9e4bdHNHLfdStvMXSylj/tVhlwufuo2uzMR0gdDo7CVEvu/w2SuQwJLk7aee7+BFC0MmBEguVkSE2jnycmVo4D6gU3S3tvNRw8RR2d+eLpzAiKX3Z22WnXBlX8KMt3bkzq1uf09vhPcsstlmejruYIoc=,iv:mjd2SYrI70w+Zc/m/jdnIJx+a1JVac554UBbUs+IKMg=,tag:rZ5vWOUxS6lJgKbmsotH/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
