apiVersion: ENC[AES256_GCM,data:2sE=,iv:OlT7kjY4gyFKyCfyAFsvediYMynjccy1TauALFk/BdE=,tag:K6HRRGNyZ393QntT9QjAQw==,type:str]
kind: ENC[AES256_GCM,data:98rf4LoI,iv:Bi81Ddd2DjRD2E6wsHVG/QtQuNtxXZmxgyglAVU+G9Q=,tag:CM+cmjqdHnGE5ThckkSOfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYOFWXYBdQdnL+NZHqjna5TNBVU8Mw==,iv:W5zwyuuGdw5HtKxwnAT9rW2eH/GwIfBUATT+J2suxTM=,tag:j3pyyGtEpyag2omwL9sBpQ==,type:str]
    namespace: ENC[AES256_GCM,data:zNMYe/nRS31rKxiRzlyr,iv:sSrQ68SLrZ1Q/EK4M7aVm2chMl/+moiMRPRxEpNxIgc=,tag:w/2voXoC0b8hhZQTtgeLRQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:JR6BJaaxd4EstL6/PXOjzSTLUeFQ5YsflQuHHbphR/kBL2lp0hOgUM6Y3hVmH3VCboqtvCetuIgkbSdL+lR4TdHj32Esg9uu/AxTkCPyaZWsPW3IU3hsWNa1N+anhxX+b+5V7fcjVOXpVig+eJkGv0hNTlFZ3j/cSLR3NzYlQYupmEsq2480l0bRdNzl3iaH9rv/qGoDn0BGt+ArVxO+hzHIUGzz7Tb1wj2UEpWx0wp1x1ooOuwicHw2utJgLcavc6zLACxtoNWx254htT7Jtraa9jTA38CL8OLRf6VQf/vfSs4+ynnZY940o9aMQAyRUXDW9J2SNn7BzQOFL2obRDvlxow08vLDm9JH+c0FJ0lba1mqKP+wkJoEttMFjXGZJ+upwqTGMBZY772RwTR6sGYhz5veKCn6t1soqrjL/WBSBFga/HZ6ciDK66EpiepHCZA47l3hHhIbuxWQuFPRRhV0nxjSQ38A/SjOrO8KfCOh2CbpsBp1teRkzIIKMPipAuCsnZv3VtmPcopuwQ3ztzQ8LzZ9hLdv72tSURMZ1DHJrfsBArc2FQMPa/B4CX2evzu+OjSww2iRFk4QWjaoWVjOwU2fQoTVL2hwxM003L4BwcjvQBoe22UqhgIucUw4C3KCfjbuPPdayUVOjKeb2SPgtnqqqAyoYOIsFdWzyUDiWy/Zpg281Jt1SFNXAWhd378zDkris7ntfUx9PpplkwHAkQxCDdi8Y5Bq1SUY8aBFQW9/REs4UT7OGzlTNk13C9VMwdsTyoJ5lWrcuGPC14fZydwNUxgH/S33tYw+VPiW8ctYj9nMmWsOBQ5mqOu+dmIpwxqEQLKgmaD0BZKdpBpxS6x1vPo5P78Dc/+PkDgRjFfp7Kz+Rr//R5aXP/IEJzREKLSvGPBWVu1fw1yDesKtXPVIZlBLm0lCG+H7d6qjhVvFbo5ExjaUm1YIsLhFh1f5BRx+QoqTVHHtiBXfKJWMFbTAitRXthNcNISO00074wRvQ/oACE3CwWVmafxGSk74vidgoMlVwQ4QKcWaLgU4s96lNWTl5V3iCEslcHooUsYyO660uuWMJWKb1wkMAQyJ0yE9QoAO6YASkWYsHCUsQ2pxjtTXEjpBrc9y2Kgwhv4LNqICtJZZkUASOJhWpC4yeeEpqT5LQWr49sUngy6cywL6Yj4j4RVN4Q//C/H4n7JuiIz/fYfvSWccoljYREN9XlVTNR5jrM/NcqIXWjNmYI4IDYirJhdV9+7axGLT4nR69eMT5SC887tEIv1lG5rmY1wlwpcypqlF+9ZX2NQfXcKcNuKjXRL2XFav3Hr6v78Jc+9aSCgHi4DheDN1ZH2/TQROGBsaT2e7NSCNS0VhRqxGeuz31E4F9Fn5NRllCK9SKebsYmC/2gnszyCEDiipU3IiKXSKA6txZmWu4olnRleVAHDRxWMhGP9HAJJGYyPmAh8vvbpj4VakkzAAlBagbTXy+KNBlpmlHZtgXaP4sUSQ6bOzwxs+5FmeRQYsNSmkiXM=,iv:m8I+9gwJtPmYQ8FyYyOZQGA4ru43v5BYFRDeSEPe1Q8=,tag:7nZ35VmMYtkAiLe0o8wOOw==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEE1cm1zTklySHlZdERK
            OFN2MEgzSXF1SVBuNUduZzBIQnNPMFYyU0ZRCnIzbFlCYU94NFN0b1k2ZVplaDBM
            YWlKT0VTVDRRbGhaZEdKQ1NRb0Y1VzAKLS0tIGx6V2FNczllK1dISS9JOXBoTTho
            b1B2S1NzR0p5dm82Q250MEt6ZEJXVkkKw93g0w0XOCIYSA4vpE7ubAMnlfdOMlk4
            46jrceAvRKWZyTFUcrF9F2rjWqunDILzU0uSTgRGcXA2Tx7MIFokYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGJKbG96VExlaEVWVWZa
            a2lJazZVYzBaVDc5SnVFcGhwRjRtdjM2YmhjClh0ajYveFUvU0JjNjlOVmRxdlc3
            R3hFb0tIQWg5Q2JscG9jcUtzR2RiRkkKLS0tIGY0S2VXbVFXUlVXa3YxdE1yc25s
            aVE3aWJsTUNhS3RoMjFLU3BOMlh5ZmsKksUKFI+u24a0gEzPeAgtK409tld/TH3S
            lIvQyKX3nqwA8qMoZnpyFHTJTMJTiQEDQNq5sZ6pO8QA5quPGY/s4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T00:42:08Z"
    mac: ENC[AES256_GCM,data:dX53dmiJ4iy3nf81N1oJr+HZPKnR0R+yMQzm1HN0unGBYXninjDNYbop+/2iT1KIVvFj6qsI8o4EYoTyW+wpKROSaihyFGBp2z3UqweKMM9PMaV5hj/DxWm0xyYJ5Yc1UPql4fAdbACqB9GPKF3s8u3g5Mwq0iXloykEwnb9ZcI=,iv:UP3+oW05XpX5e7aTumMeWXMD3Xoka3jwUo89Y3EltrE=,tag:b0i/emBC1ufnfdSxdIapOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
