apiVersion: ENC[AES256_GCM,data:2sE=,iv:OlT7kjY4gyFKyCfyAFsvediYMynjccy1TauALFk/BdE=,tag:K6HRRGNyZ393QntT9QjAQw==,type:str]
kind: ENC[AES256_GCM,data:98rf4LoI,iv:Bi81Ddd2DjRD2E6wsHVG/QtQuNtxXZmxgyglAVU+G9Q=,tag:CM+cmjqdHnGE5ThckkSOfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYOFWXYBdQdnL+NZHqjna5TNBVU8Mw==,iv:W5zwyuuGdw5HtKxwnAT9rW2eH/GwIfBUATT+J2suxTM=,tag:j3pyyGtEpyag2omwL9sBpQ==,type:str]
    namespace: ENC[AES256_GCM,data:zNMYe/nRS31rKxiRzlyr,iv:sSrQ68SLrZ1Q/EK4M7aVm2chMl/+moiMRPRxEpNxIgc=,tag:w/2voXoC0b8hhZQTtgeLRQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:1Pco1dxiSw/5Ns4BwKn13LMmnazi6iCSNF7Gy9zYKua/7GToIw+CLmovmsGMwe4tb2ayj/N4t/RiDlVI9wo68v9eXVHrDtUdTVA8OoQ3PGj9cQabNMssqka2Lqr2T1Y9fpzXFB1P4qpb3Qnby8Fz/F/mIhnucra8qxudN6v17YT6V6TSerDmQuvCZvEvD2CnEcP6nSE9U6AwvKF1DhK8ysMre3u0giY0YwqyFLCI98yrGBb8swB+IahrXyO6+4g0j+6wk/J/e+iEkwiYDJkg5eha41kx8bY9V2x8V0pf91kfjfHj4YnJK7I6UfAxFLbDlp8ovl5cwLENhpsW+7QMoMGe+NzYhe9iw3yx9637JDCyaWmjAKuGbIkheceFGuVmU7zZd66S9VUG4tXLf2T5jBmY7BzXQD8LwuCvbxA1E1c2ShPC6EdgeR8/lZuZafZe/Z23O8i+FEmRUGN2fm/HD9ySYVzJFW0cwhLzEGgDABXehepnrQnUtujRltfJevyYiosFCyw6axKl+xYRpHE/kaBW3FAWbi1EzRXHcTqSf1SCqwOkfyKwQg6z9ZbrVuyBNF0LzDo1V42TJoG2tVBa7QawEm8tapdh2O9YGS4nvHDSv9FMrGwc7jJu1+ZJD/OOFWOmM40dFRs9rZ+bCdAMjpOGsflN7Tb+qRekGRTTthVDLJG8hoTlFbFBjo48LtzoEWjwA6euJHcETARhLMsjOzGd+G2GB91y3p4RzrGSdcsToBB8R2A9rUjf5juPXV4LXj+eoipC48bTQnfBUe2d9MiCkq9Q0G/f+xPExZp+XRqAar0j0WSH9xqQ1Acg7gQnYAMFVfCelBRelPmr3JkDSTFRLBcoGWAP18NOUhxB8kY6Vt3P7ppS+tRYHQkUUKtLsukebHJDI1f24I+V0kF+5nuDX35rtI0h+YMb3x88OAA9Yi+j6+0JroNTuhjSpvi20TBoMeQbIMQjYYu5MA5Jb6Vx9EVkv36PgiQU130C4IroCKtSUrbonL54o8IyjgpG2SdMlhVrd9YsEoC6nBw9HSALKlu3ieywVR0uwZgPnUc8orMMfckHWMG+UL5br7n23lPR+oELYsuw7nPoXvs3UPxPuyUG+T9tbMXvRScMnKY+a9aZU+PPOk07M4m9N6vuUaiVBf+TLlAURpuP2e7XnP6pwnwrxpbvxIbuvYGLV0+Gd/9vrpUH4aW8LzSHFYa+iOgTTmzdgARou6BWYGP0khykL3NdgL7bK/pkR61e6ZaxkKVjTbTybwOwj+i2zX4RPrS0vu0xvLVG4ni1VQFxhpY3BK6K4+wHSVCm8ko9pA9l7PlZYbAxnKWxLmdnIJj4cQuwLj/pnKuA62CRv+7zFUhDm1mm/t4BUyDN91TBg5eHRTZyDKJpHU1Enm3uB6Y1bX2cJipWJ9BGgsIqMs+tTnmgcQF1JWzwqt8r5118FGHDUjbj7bj0pZP0eBDS/SwJjavxOdmlgZkYh+VySjYzujPN1qxa1ID9G7tOzea1qH67,iv:kWfeW0OUjr5tKEcDM2ovEryjQ9bq46iXP+GasK2jMGg=,tag:vPN92XUeIacyuWLBcgcMjw==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEE1cm1zTklySHlZdERK
            OFN2MEgzSXF1SVBuNUduZzBIQnNPMFYyU0ZRCnIzbFlCYU94NFN0b1k2ZVplaDBM
            YWlKT0VTVDRRbGhaZEdKQ1NRb0Y1VzAKLS0tIGx6V2FNczllK1dISS9JOXBoTTho
            b1B2S1NzR0p5dm82Q250MEt6ZEJXVkkKw93g0w0XOCIYSA4vpE7ubAMnlfdOMlk4
            46jrceAvRKWZyTFUcrF9F2rjWqunDILzU0uSTgRGcXA2Tx7MIFokYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGJKbG96VExlaEVWVWZa
            a2lJazZVYzBaVDc5SnVFcGhwRjRtdjM2YmhjClh0ajYveFUvU0JjNjlOVmRxdlc3
            R3hFb0tIQWg5Q2JscG9jcUtzR2RiRkkKLS0tIGY0S2VXbVFXUlVXa3YxdE1yc25s
            aVE3aWJsTUNhS3RoMjFLU3BOMlh5ZmsKksUKFI+u24a0gEzPeAgtK409tld/TH3S
            lIvQyKX3nqwA8qMoZnpyFHTJTMJTiQEDQNq5sZ6pO8QA5quPGY/s4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T18:21:50Z"
    mac: ENC[AES256_GCM,data:WWlZhDKijwJD+5JYVO5QzBHBZ8blnPFoSVGAqiJeQAtn430URwaaK9Wv0BCacOaa+adHnIldT6PmBnEQ7+sNazY9SrB0SYDFzMjokrkuZD0/GBZtkjLKLCtbIehO6lKdbLECn4FY2PKw4XXFm55SM3wTMOnzCFfd7OD8jb9737Q=,iv:XyxfxaaUBNgG48YYBjmCSX1KpwLnm/xl2FQfJGebGiY=,tag:KioFCqNtavQxecmCt1t0qQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
