apiVersion: ENC[AES256_GCM,data:2sE=,iv:OlT7kjY4gyFKyCfyAFsvediYMynjccy1TauALFk/BdE=,tag:K6HRRGNyZ393QntT9QjAQw==,type:str]
kind: ENC[AES256_GCM,data:98rf4LoI,iv:Bi81Ddd2DjRD2E6wsHVG/QtQuNtxXZmxgyglAVU+G9Q=,tag:CM+cmjqdHnGE5ThckkSOfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYOFWXYBdQdnL+NZHqjna5TNBVU8Mw==,iv:W5zwyuuGdw5HtKxwnAT9rW2eH/GwIfBUATT+J2suxTM=,tag:j3pyyGtEpyag2omwL9sBpQ==,type:str]
    namespace: ENC[AES256_GCM,data:zNMYe/nRS31rKxiRzlyr,iv:sSrQ68SLrZ1Q/EK4M7aVm2chMl/+moiMRPRxEpNxIgc=,tag:w/2voXoC0b8hhZQTtgeLRQ==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:ItJzIAHWHHxlU7qPw7M2LcC7TuGNMyqqIsNWZYH17tsF6SzRo6ov9gIgAz88vMujNF6EYXSDDu/Z4pZF+j6hmxj4HGOwvQIWE+H7eUGvdE5SU3gw70cFgcT0+95FeoRMn/nq+kbtqDqYIjRNM2Xce7UYlkJg6WXR8ZT1Rw6VghcfFtaA7RUiD3gkCQGFJiSr1scCxUveRZpQeQoK7CkUkdDizbLHU8bmd54P3IjOgj0gGvrlBHXX7Cb9qqhv/+fHQXNZwMb5mIqys7A7imnb7P0UL1C5E8OriT0agiyTc5hGpAWux8ON/k6qvBSOyycq1YXL21DvPLokSJUAeSBCnSp066PbRg5XFyvJg/bvcPcKZJkAAOAg2yqc7pDsoVSN7fwgapkisI4FlivGqO+OXagGNlaQRLK2J1sq9B4XeqQDuy5JcQC0QaVm8BiQ7cWA80nV0uyOz+U7jniVSBWeUFKOglzSZBWM0Wwlp5ixKDP7jhK442ExvRnZaIjv0RtSLEJmAYyPi7zBfFk/qBcNXQfRw9v1gj+5wntDnsumaWDEo0fd2QR3C8Vj/Ph+ECcEcA5TQk69wRx+iYKk+lJfYoFc05Gny7EdhI1maji4UBR8wPrUuuDEaLFnDqWh58CVS9+IBBN5Zjtk7oE8aU93lPwjy13yUGrx6ZxSeuhYnRedqjFmHmR+qYL15yXoUwXloAAG8E++xlc4ZwRuAHjnIbJ8nKV+/dMr4usX4k+FqsnMSf6Ux51noHVzIfNTRLTdWsNYMInQPOWGC16DH/pTvFTHIwBb7GpDKb2maf43qY9GWqd5depldNwtRz020AKlqvZNqbWsKI/c9xcMpbelq/FVO2pm0Vup/fujWydc/fMVVerbBLG1DSos3MhxGoTZiAzKCfJKzhTU7qjaUraewIW2oWNW2RDkRQZkHnb4d0mBiWfnn4CGAWsbWt+sh9myHwzO7Zg3fW2st6ibnyV7F8eEhs5FTC7/unER+9T0Cglm/oWRdC/o7Fp+NdbunSCQctsBkXNwpMhNE5KFtSAVRe1rDNeZXNNhe0CEi5/nnyq3hms53DGCbl9ipRb3XXhNgCjaGs5zF/Iv9iT3iIbpgABcwMRgiXXpZiuJ1uE643ui88ZeFwbrKX1Lp2h9A/s480oLzy/ep8OLbaKZjlSVmcbpAgipi/rbIUPk9m7VlNCaq1JlmGsbE9L/9RGtnUFQ8bNaciBG3BbyQTo3IAIq3UAVgfPyrmGogoIjwXtagItRBfDc6enK9vNpvD5EO1v64UU6I5wnKdEcNjKaup/L8wuqO0BsoowUKVQtjCH7TiyiHjjyrEN0JxEwabV6UZ5B6j4qks0Sz5MHqKC9YB+fC80oY7uW8dM3wGwT9LINZLR0FooGuVWFSMnku/Id0go+sgH9kEc1wFem91I03+cXGOiVbHA/DnRaoCrgKhtMC413LIncTS7tioUdH11rV4Rd2moVKYlAEfJkvPlrmijPPtqwQK8TC+IAT4wLuspJKRP/XqSc3FA=,iv:m5DfzaHzSWg0/j7NlG8+LlOXAlSMier4RdWWLVob7Vw=,tag:y/uEDlXfNu0qDcrXpI5Mrw==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEE1cm1zTklySHlZdERK
            OFN2MEgzSXF1SVBuNUduZzBIQnNPMFYyU0ZRCnIzbFlCYU94NFN0b1k2ZVplaDBM
            YWlKT0VTVDRRbGhaZEdKQ1NRb0Y1VzAKLS0tIGx6V2FNczllK1dISS9JOXBoTTho
            b1B2S1NzR0p5dm82Q250MEt6ZEJXVkkKw93g0w0XOCIYSA4vpE7ubAMnlfdOMlk4
            46jrceAvRKWZyTFUcrF9F2rjWqunDILzU0uSTgRGcXA2Tx7MIFokYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGJKbG96VExlaEVWVWZa
            a2lJazZVYzBaVDc5SnVFcGhwRjRtdjM2YmhjClh0ajYveFUvU0JjNjlOVmRxdlc3
            R3hFb0tIQWg5Q2JscG9jcUtzR2RiRkkKLS0tIGY0S2VXbVFXUlVXa3YxdE1yc25s
            aVE3aWJsTUNhS3RoMjFLU3BOMlh5ZmsKksUKFI+u24a0gEzPeAgtK409tld/TH3S
            lIvQyKX3nqwA8qMoZnpyFHTJTMJTiQEDQNq5sZ6pO8QA5quPGY/s4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T22:38:16Z"
    mac: ENC[AES256_GCM,data:SPkmH4mPmj8mJuyJULe32j274wr+KAVcL1Og0tavWxpvMbB5Hb8fldyDAdWTV34ughfHFB/v5ImqnCwcBBOaWIp5S5w8sZwltpzQ6FzEQQnBmdCwoucDI6sKlqKii/9A1S7jRHhmxS8j5FEBBonqKrrdBPUgclMcT6ig25XR63U=,iv:mQShUJ2KFev039koPb4T4QWJdqQLnlcRt6PWhAEugW4=,tag:yPeUGBjywaVnD0rbXt+R8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
