apiVersion: ENC[AES256_GCM,data:2sE=,iv:OlT7kjY4gyFKyCfyAFsvediYMynjccy1TauALFk/BdE=,tag:K6HRRGNyZ393QntT9QjAQw==,type:str]
kind: ENC[AES256_GCM,data:98rf4LoI,iv:Bi81Ddd2DjRD2E6wsHVG/QtQuNtxXZmxgyglAVU+G9Q=,tag:CM+cmjqdHnGE5ThckkSOfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYOFWXYBdQdnL+NZHqjna5TNBVU8Mw==,iv:W5zwyuuGdw5HtKxwnAT9rW2eH/GwIfBUATT+J2suxTM=,tag:j3pyyGtEpyag2omwL9sBpQ==,type:str]
    namespace: ENC[AES256_GCM,data:zNMYe/nRS31rKxiRzlyr,iv:sSrQ68SLrZ1Q/EK4M7aVm2chMl/+moiMRPRxEpNxIgc=,tag:w/2voXoC0b8hhZQTtgeLRQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:YkAssv8CO52xcA81ifgogyY2n2XPDVwGmAjOtI426DAKNZbXGTcexEXxMKEGLNzuCCnM4bkIvkbDh79+wew5m823P/1KqbJ8Y0jO0XNbTkyQWf4FIeRASfgQvzeYChAViqYqlmg3w5THMA5ll3ARmG/LmKZ01CXT2cyC5yOB7nek1SwvPnLT6w8yw3pVmgCA4bObkgcSfz6uH7cT89/0KvlLEXC/hHocM1mJTDn8URh4a7ncbAlxUaT7PIpf1LgqXDQa9LT/cYKVyjKNRnPeQoDSV499X6Oxs5nUnEOfpv/GipixYCrMS05SL0wgEFVCmIFJ2XxOCw2sMsJ3vJQLVSnrPGwDcUEZUnwLZ4FyQPoL3aJbVvv6sVeVPkovLOeH6XkqGx7FsfAelgZA8VeeMfLCaR8QvMs5eEJdmO18BozRgPw9jGW3c23Aie+SEniSk3KP6ivIJ8VFk7Q/oHXSnsuLASaw7+zz19ok9ETmIYiPC6rwnuL3Qgz/6LfzRZzAXvhUcNgdV06ZVYnWyla/sYuhp+j0ems8pcrxkm8ALs0qfVJVn5mzy4onlP40qBmGC3AFplCGJes8X6KjfuftD+iMTmRf2NF3sNmAt2jvXMV10YTnd6pz2yqfFKxGcoIioajBwONG5YjuRHflljGna2JewLsvdoNbX/W4c+wG5/a8fe2p49PfxKTYxL65AyAPofm1MLcnPm6poFtRKIVR6m4AzGArYsPq+KAHz5yuiQeqGRw0qRy5ljgwm3USj2Lz/BEV0DWK4yLhnvxgQnwGYiuPIqZmDocX75iSweC3TUuRZtWakywfvWBRmIZQ+KS43jBKV9MBF6+dHKfZfCsIykznPO8Ckz68n1CxmaeMujT+yVV7jlDo3RCa/vxQXzgX3c3h+HI2nAHqoipvFZUkeD/Pig3S/TA0fwKhDcEICOuGXDwsxMX5d7Ur5QJ/CdD5RyJrVKRi/DZYMlPWhRdh5CREX9GFCXqIO/Fg/U5IM4ioPK4N/+yI0tiHuv7boVx8fPmMgUW3Zl4hclNoAru8TV+D7dhyivSZNgkqRqIGluFTm8kjYyrybU/T3uMhe1cTUx5VPICS+x0AIzZb2iHhG2ysy6ohxGGKJTYzNLl6e+SUP4Gph3rVY9zRNZ5IrPBU/DhHCzjq/rzZtFgCKgVQ9lTW0tJvI+19ODMBkl1D4Cbb54t3sIhC82CPb0pKATKBLyDxYsQ7JV+YrRWmRTQdbDARd+dI7gbWbo3I0GomBVAg2mdj5sVS762OJ96JYLfGCjAJx46lghRpvG7jb+Cfxb28kkQsEDVgIUN5AHM4PlTZZF81vL4LJxE1oS6Tw7yfpyGfY89wxPrtxU3TO+cG1Q2bDjGzqY0agpHchmvvLWQYZ2Ua+D6Tt6WpDJMmUL6EyLwytsqPgIlRC7CY7Rm9FL9425qTxtcdR01b3L4lYQu8pDyKkO0n9rKlx1Ox5q6WJ/pf1GmQz6Ev7Rd9uA6ueqZvBzWDpdoROJDmvhdDQg3vhiNo79kg4Q69lF6Rfpw=,iv:CZ5Qye0lnSFiH7Ickf7mA43pz0NzBLgh/EygHdPQNGw=,tag:/TZJGJ7Z4NyYTY06aik+4g==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEE1cm1zTklySHlZdERK
            OFN2MEgzSXF1SVBuNUduZzBIQnNPMFYyU0ZRCnIzbFlCYU94NFN0b1k2ZVplaDBM
            YWlKT0VTVDRRbGhaZEdKQ1NRb0Y1VzAKLS0tIGx6V2FNczllK1dISS9JOXBoTTho
            b1B2S1NzR0p5dm82Q250MEt6ZEJXVkkKw93g0w0XOCIYSA4vpE7ubAMnlfdOMlk4
            46jrceAvRKWZyTFUcrF9F2rjWqunDILzU0uSTgRGcXA2Tx7MIFokYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGJKbG96VExlaEVWVWZa
            a2lJazZVYzBaVDc5SnVFcGhwRjRtdjM2YmhjClh0ajYveFUvU0JjNjlOVmRxdlc3
            R3hFb0tIQWg5Q2JscG9jcUtzR2RiRkkKLS0tIGY0S2VXbVFXUlVXa3YxdE1yc25s
            aVE3aWJsTUNhS3RoMjFLU3BOMlh5ZmsKksUKFI+u24a0gEzPeAgtK409tld/TH3S
            lIvQyKX3nqwA8qMoZnpyFHTJTMJTiQEDQNq5sZ6pO8QA5quPGY/s4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T20:24:16Z"
    mac: ENC[AES256_GCM,data:6iZpeK7LlmKZIm5gKBo8U7wR7to35bIhansMiJJiocqSWUE9lS0P06SaPWX8PJiZ+MK030/ZfBUKceSSdaskELAb2bXDKytimTlbfSHzev6yS+AZdKjCOjLeIp+F5zDz3Gju2BO5lJbQYTd3nbKZI4THfFXjcyRRE+pGJLBIg7E=,iv:23iweiFmCVtowd8eaPHxkzcBWokibT5JiSKttpWnSHQ=,tag:UI8tPkj4nuoJ3COfL4TGXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
