apiVersion: ENC[AES256_GCM,data:2sE=,iv:OlT7kjY4gyFKyCfyAFsvediYMynjccy1TauALFk/BdE=,tag:K6HRRGNyZ393QntT9QjAQw==,type:str]
kind: ENC[AES256_GCM,data:98rf4LoI,iv:Bi81Ddd2DjRD2E6wsHVG/QtQuNtxXZmxgyglAVU+G9Q=,tag:CM+cmjqdHnGE5ThckkSOfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jYOFWXYBdQdnL+NZHqjna5TNBVU8Mw==,iv:W5zwyuuGdw5HtKxwnAT9rW2eH/GwIfBUATT+J2suxTM=,tag:j3pyyGtEpyag2omwL9sBpQ==,type:str]
    namespace: ENC[AES256_GCM,data:zNMYe/nRS31rKxiRzlyr,iv:sSrQ68SLrZ1Q/EK4M7aVm2chMl/+moiMRPRxEpNxIgc=,tag:w/2voXoC0b8hhZQTtgeLRQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:qdcOEv3s7PxFatrOWmiZ8kcwUHTmz3PlsI9g3chHtOnOqv7fCjDSbobCRxaXtCpVUeSxzOv7TVcLT+ZUHqng2EA513ok6Q6hpQpgVHVz4bRFLScDzfWUUlXanXy60PRfm5AbXm/U0FtUmLBzBZ5c/Wh2CvxUACWmmZfQCr2u2/pZoK+p8AVtRCxOQH4OrYweh4iVxedPzDoF9H8OHVawGXotXjDKmkFddJwidnPOH6rxGHFxE/dYUZmQUYOHjQxhKa4gzwCW6pd5mqGSfrL67Ko2DKtQcNXWaKws3Mo+BSbxGDofscrUXTV1v7vIUhodRr0LoAl86tIqaGbYi70NEG1HdmojGck6bAmoyWfFFn0FZfZGTAIqvJtjbWoNG7Kh6rukUCXIOyaM2Jp/tIdgEtzyn9fJZnRXt36hNZAOnLPXCEJHOz7qlFgwmhrvfLF6vtDkiKI662WUm1grYio+SiG5jSBcjQ0nP7dL2+/IdMKoHsYGjdhYy4cmlGGs3C+V1K2mBQIdpAU2e/PS/Mzeu5iR1vlCXJ7JJ+0k8J4yB/AqGEIgL0j/luNiMqMe/tlby9T3Eu7XAl5WgXuVdZymghHggvkj3PECUO2pyNNE3di+KtF49z2mywAOcaZCGasbwXCGaM2OGee5YbBggzg6ei4J/Bb/DH5UUs5wDYOxDvyy3wSkC24ib0qWWTEAKuh1BeF5+wVNrWW7AoFwkRMAv2bwq9CLy82kEKx/8aARaQXcBWEwSfx/JQiR2+ZVmwns1aUeTjBtxXLRwhRdDJpPMOBT5/qTextSxg14JeYcpAfCPegKto5JsRq9sbr82DAsixHuEpNruCx/eY78+JFOHrP7yX4zK5VRaSEAb0sb+D0XCLpkzmQJI0n3O4p507M6zxnykGUhoLkJyrpo8LHMn/5BHKZcrSNQCpeW3wUORzdyq9EnP/f82F4K0r1920PFA2lTy46x7VzJerh2YoSq/IGV7spaKMuKPE7+STsWTViUBh8qMWtwQNNja56rVJbltoaiqng+LCAQ0bBEjBgnYDzOx+55yxNQkdibBF8yGtdGCE+mmiRw1v7E0z2xUvbAjDEjv52uyPYktT/S3xCtqe5Flep/yuStD/i2OavA+a+rNT+zxViAEiDP8ApxORXm2kK2Lad1NC6AKF4s8Tr75KSTgvgW3nhI0QDG6u0h7mg4yHV2rO/VrYxfwVyoQauaOideb2zDw0J2h2FVrK+Fs4CMHnJWu76Ea/5RP2qS+erjmEZrO1bkYSlrLmunrZ7jsz6tJi2A/s46CO8g62UYBpmIRJ2QBxhWlZz00ujmoVi7/ZVJsRPrsc4axNKOzp6MQP4AbBs1w3S5yMcXnu56YmGWlYItJCjXEhPhyR1+c3ACBRTYyEmJvrSbeMxNTqXFgiZh+BY4BitHI6HhB1ht9eEIfpa4p/hHyir7NnM/b9hmOpTk62pR0Wk8w5Qo4btriEP+/Oc5Wl4KGW/aDev4moAKXTmqQk9Vajxvz40dvtDYglcr+w08dyuQ0Truv3YH,iv:ZZmpyfgE5WFsKoavp6Ic6mfkc4S/7Gf8vble1028Fzs=,tag:R1lU8kTXlBz6A39p//wshA==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEE1cm1zTklySHlZdERK
            OFN2MEgzSXF1SVBuNUduZzBIQnNPMFYyU0ZRCnIzbFlCYU94NFN0b1k2ZVplaDBM
            YWlKT0VTVDRRbGhaZEdKQ1NRb0Y1VzAKLS0tIGx6V2FNczllK1dISS9JOXBoTTho
            b1B2S1NzR0p5dm82Q250MEt6ZEJXVkkKw93g0w0XOCIYSA4vpE7ubAMnlfdOMlk4
            46jrceAvRKWZyTFUcrF9F2rjWqunDILzU0uSTgRGcXA2Tx7MIFokYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGJKbG96VExlaEVWVWZa
            a2lJazZVYzBaVDc5SnVFcGhwRjRtdjM2YmhjClh0ajYveFUvU0JjNjlOVmRxdlc3
            R3hFb0tIQWg5Q2JscG9jcUtzR2RiRkkKLS0tIGY0S2VXbVFXUlVXa3YxdE1yc25s
            aVE3aWJsTUNhS3RoMjFLU3BOMlh5ZmsKksUKFI+u24a0gEzPeAgtK409tld/TH3S
            lIvQyKX3nqwA8qMoZnpyFHTJTMJTiQEDQNq5sZ6pO8QA5quPGY/s4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T00:27:04Z"
    mac: ENC[AES256_GCM,data:2cwxnihRTaSK0I7XzuZQC5hPdmn3jVZV2TcfT5w3KS4mX+y1ScDqgN58c7wHTifyNOSQZGgPS1X7+t7aLZ60PmLuLbyjd3CbvuJ4F2LppTnOBMUePFwf05CzSb0rvY493FZGi7D13g2VWH5timihK2uof+2RY6RLMDzQ/T8xDtE=,iv:u4/MAfzTt4LAQoyniluZvGxyN0TK7RIUoW/4QiZc7Ks=,tag:BX5a/BMeut20oo+KhEfErw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
