apiVersion: ENC[AES256_GCM,data:9Z0=,iv:oKhJh0EmDSpeTcQhT2hPdmA0DYuzXI0xiG20j9T2HOE=,tag:gpwgZWLhHN3v51OaGr1dkQ==,type:str]
kind: ENC[AES256_GCM,data:zfGxu11w,iv:WvWMsiBCnCymXWgq67Pa1Ba1saXS2NQej9ZpWwkZibY=,tag:p25+ntPknItrgORHIcJ7PA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oo1XktXUdO2E41YNCTOGv3TxImLNyssKcboheO3G,iv:HGt014HV70SI0zAvkMEkMcWOUynKDr7IyK5SW3/LwlQ=,tag:t2Zxlbtxo8iScgX+CwIadQ==,type:str]
    namespace: ENC[AES256_GCM,data:oxMQ7iWjIU6VHc7HSoEo,iv:LrGzDQGIJ1G1Sl9ONbk6yJFmJTfAMjvDEfweh2QefBM=,tag:W9cM89HjL+qXLqMQdnaWhQ==,type:str]
stringData:
    config.hcl: ENC[AES256_GCM,data:fOMdHXJ+gCup7Y8r6W163pnxxMhiNGj8qDnQrf0wnV+vdNJ0pHWNUhFKPlbOS/GSAivjOLLV0Oj6u4VyxeMCtMnpDNfmq1ZoXAPGgjmeBxkKOJxs30cUvVmEEVNjDXaQL8vEOakOq6LDtJmxVyz072WsLJPUxJNQz5ejpzwkrMsOmXcQYjx/nnEDYouj/l4A39VRi2Docn27AxSG6fBLk600oQf2jsOi+pgOCCxVrsfAljWLM0LMsXDl5FFq+D5H+3VeCA0jjxyhMNFbvq+GHUvW15ZDltqua7ZaKUYV/cPkryeK7aDODFAa0wQS8SQ7oSBPfHMCe9ZpXQ0wLrEEfHPhhG6SMWroNTHqfA21zl+bmEgAhiMYccAQFQYOGhUBqxHzFph+hjzwQLGeLj9UZJXKQhkOQJxnGCKZ3Pbefz0qbLuEvb9QC5veJnJ/pPwgYTAcCj3bxqkhu6dYRxXlNy79OdwscUL756RyQ4oamPsAwIsMjBWzMtQmqwEfm1Sihka/ER4Xgerbom2ibKAOqYTz4D7us/lpKrSUiyC/eaOGMg4h+xAbBAIDXs+TENVy/kpCmOWD+sLUZ/nMkY/GFxl2S3ALltKlZPHtnRhIbnmjZgrZqm5gXPTmXONbksD5ZZbO54tYJCiH2j4zODkOu1ChbZqtSQHzXCOh81UjQE2gHhNCKo7P39YzaQijGC7mqQ31UltcD98Sb0z2ze2urw==,iv:jw9cjBlWaARpRHqOjegV/6yJDtiJPUj21ZMQzZ1i6nk=,tag:MgOwAQJGYoAq+7ci5/t7zA==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMDFiMnVYTUloSDI0RUJG
            MGFXdGJQUWJCdUxVVFdRZ2s0RzJTTEtaNW40CjBTZFRYcW1wa2t4bVJxTUZTNHFK
            MXpzRDVmRjdGV0FHTEcvcFBtRFpHbjQKLS0tIC94QlZWNytFOERmcXFOd3d1cGIw
            d3hETVFKM3YzTDhFUEpNMjBIMENoYmsKkth71Xy03k5cGJPLYD6VYIusF5DZaO7b
            Bpv7nU2pMOfvWM2aYR6rvlMeZwIwT/s3i8AUwEQk5+t38leJIoH9Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOXRMeUZieHpuRlZZNm5Z
            UkNlNFE4UkpieGFxYU1QeTdqMzYweUU1WVRJCjFyZjZqbmNIVUVCN3dhaVdYUnFP
            QXZRZnc1TmZkcWo3eTJBdWs4aEZpc0EKLS0tIGpDZWwrV043K3U2L05OeERwL1ZY
            ZC95K291TDdBdmVPaHVIU0QzQ0c5RFUKirhH4n5Cy+zyYFH1VwfuUGRuuoqWL+1c
            nOF6ipJ3T58lKlAb+rExRxoyss0IzxqpJ3B6i7DBYoYqM/4nXm3AlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T00:41:58Z"
    mac: ENC[AES256_GCM,data:/TxMV24zVCKhMo6Oi3/ZFihp3oFTpQvDiZjlMpeyT9Ht68wSJc2D8Tnzz5VZo7HarceJ4WVCeSQpyReZhrPn58N1PZHsCViFk2vF9mK3Hu6ec2lgwW+t5qqX+9SdMsxPS6wkWX/4Ip5SdUFEcrnH9XIC56BLRNfEEgSUdUWnUCQ=,iv:uuo7vv1pTCWyGFw/vIVlSyX6IkEzURgpZ98JEphY/QI=,tag:W2tpOBjFfcsxwNIHH6BDgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
