apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feedback-fusion

resources:
  - routes.yaml
  - indexer-certificate.yaml
  - indexer-client-certificate.yaml

generators:
  - sops.yaml
