apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: feedback-fusion-dashboard
  namespace: feedback-fusion
spec:
  hostnames:
  - feedback-fusion.randoms.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium
    namespace: default
    sectionName: https-public
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: feedback-fusion-dashboard
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: feedback-fusion
  namespace: feedback-fusion
spec:
  hostnames:
  - feedback-fusion.pu.randoms.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium
    namespace: default
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: feedback-fusion 
      port: 8000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
