apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cal
  namespace: cal
spec:
  hostnames:
  - cal.{{ .Values.domain }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: public
    namespace: default
    sectionName: https-public
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: cal-calcom
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
