apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: event
  namespace: event
spec:
  hostnames:
  - event.randoms.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium
    namespace: default
    sectionName: https-public
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: event 
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: surrealdb
  namespace: event
spec:
  hostnames:
  - surrealdb.pu.randoms.rocks
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium
    namespace: default
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: event-surrealdb
      port: 8000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
