apiVersion: ENC[AES256_GCM,data:G64=,iv:UVgo6uG7N9/QvrIbw+B0DgTkNjWuutQQSlG1FgkQOpE=,tag:jkfPDKuhoXuNP2EYrrMzSQ==,type:str]
kind: ENC[AES256_GCM,data:PN3aCwmi,iv:1n+tq2LhoejahXcEqHljx5QodwDVPRPUIRMlpCMnVd0=,tag:8rPLmeO3Ujoxrjz7qf/vpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0YtPE09wwZWbU0Wk5L7CGdfDj9WD,iv:Pg8lmpG/hPigjo70AtAXjiyTL2xhTH/ovtQGwev0Mok=,tag:a7njnZZS8u2Flds3CPi0Tw==,type:str]
    namespace: ENC[AES256_GCM,data:AHy4Dmo=,iv:BG1Sc8gvuJX18TbZ7FlwuaTyerd64dkb8fDeXdDuY/Y=,tag:+LWBs/CRm0Vd+cQqVt+3Hg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:Wp9xqt4LTki43tXsTctzwH4nb4goDYFTsks00rYskbDLr58bzvkdYya6XWc6Xb6Rsq/QKcnFfg91G6P4xuTfwf7Mgn2Jkjh7nc07lcb2YO0=,iv:fqcfCyB/ktvwzthYeeea5frlfwiguvnhdwVHmN5CcXo=,tag:tvFuxzsVlmJ/tyRo7WpgCA==,type:str]
    username: ENC[AES256_GCM,data:+jHNVrnkR5mkZeY=,iv:1H9I+L4vcXhFr3J/BSHihCa892pt7bHH3QhYngHbwtU=,tag:Yhqh/SUh+HEPv7BwJdkQ+w==,type:str]
sops:
    age:
        - recipient: age16mma2m563yzghre54wdulnckg2avawj8qsftgnuq6e00x7lcuefsw28vr9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZm4zQzBubXdHdmdERnNs
            TnlielB3bWNwUm94eDJHWks3TGdKaStJYkRrClo4NlltSnBvYUNjNDdkRERpbXNw
            ejlMOUZBOUhTUFdYQWNKaWlTZVczQTAKLS0tIGVkMmk3NVFBQjlQRXlVL0JnWXJR
            SmlRUGxGcUNUQ1BsWWVCVW4rMUlVeDAK/9IPe2eHxabw+tRXS8lnkqgyk6ueGeE1
            TufpDuDdOAhqeLJnTky2JmLWtJwPLYu0+MV+NqkOntnyvHmf/FSd8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lpxxu3tya3wprzs9fm6hu7z8fc7fdh7k0qyk8tp58xfp8ujm835sw630st
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMXgxOHd2OTNCOHZpZHpF
            QUtsMUg3MDNQRXFSTGY2dmw0WjNpSytiSFJZCkVYQWk2WjFwSS9UZS9wRFViRHl0
            NXFVKzJhd3p1SU1BZ243dkQxZnl5dFUKLS0tIFlBYTdBdHhYa3dLL0RkSXZHQm1Y
            MzhzdUJRVmxyaUZWRGZPZUh2R1l1ZzgKMKm1C/msIxsofBn6Jdcfqo3Mc+CDqlNI
            Atscrb4rmRPD4D2G3vEkQ6MBMwl03UIakzi5kLYRxXsVXj/51wj3TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T15:09:42Z"
    mac: ENC[AES256_GCM,data:a6kvZ3laO++C6hur0/gG2HOmSl9N3tTV/CWdjpgBmmobGqMERzUcwsHSxoZvW2wf+taKR6OEDnMmyckb06rD4tfoiZvHIE07Jtq0uFbSbok6XIh8g3pQzBJWPTqH4Ijw2eHJJaFR52sBzzXf6C1PCGt7VRWgncslMcSN++9oAOo=,iv:OdT4LrH6G9uAb8XEJQw/xbLhIH0XGBl4ha9Nlq67Go8=,tag:X8YVCxSiMmhzQYNIFtOcQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
